use std::{io::{Read, Write}, os::unix::net::UnixListener, thread, time::Duration};
use harness::{WakeDeliveryAdapter, WakeDeliveryFailure, WakeDeliveryOutcome, WakeRequest};
use signal_frame::{NonEmpty, Reply, SubReply};
use signal_harness::{DeliveryCompleted, DeliveryFailed, DeliveryFailureReason, HarnessEvent, HarnessFrame, HarnessFrameBody, HarnessName, MessageSender, MessageSlot};

fn request(slot: u64) -> WakeRequest { WakeRequest { target_flow: "cf7879".into(), body: "wake body ✓".into(), body_sha256: "e7d64ad752ddd1632c92419e9704190dbe549c8b4d91ea56d1ca61f0acabb0dd".into(), harness: HarnessName::new("fixture"), sender: MessageSender::new("core-checkup"), message_slot: MessageSlot::new(slot) } }
fn server(event: Option<HarnessEvent>) -> (tempfile::TempDir, std::path::PathBuf, thread::JoinHandle<()>) { let dir=tempfile::tempdir().unwrap(); let path=dir.path().join("wake.sock"); let listener=UnixListener::bind(&path).unwrap(); let h=thread::spawn(move || { let (mut s,_)=listener.accept().unwrap(); let mut n=[0;4]; s.read_exact(&mut n).unwrap(); let mut b=vec![0;u32::from_be_bytes(n) as usize]; s.read_exact(&mut b).unwrap(); let exchange=match HarnessFrame::decode(&b).unwrap().into_body(){HarnessFrameBody::Request{exchange,..}=>exchange,_=>panic!()}; if let Some(event)=event { let frame=HarnessFrame::new(HarnessFrameBody::Reply{exchange,reply:Reply::committed(NonEmpty::single(SubReply::Ok(event)))}); let bytes=frame.encode().unwrap(); s.write_all(&(bytes.len() as u32).to_be_bytes()).unwrap(); s.write_all(&bytes).unwrap(); }}); (dir,path,h) }
#[test] fn accepts_exact_harness_slot_body_and_dedupes() { let r=request(7); let (d,p,h)=server(Some(HarnessEvent::DeliveryCompleted(DeliveryCompleted{harness:r.harness.clone(),message_slot:r.message_slot}))); let mut a=WakeDeliveryAdapter::new(p,Duration::from_millis(100)); assert!(matches!(a.deliver(r.clone()).unwrap(),WakeDeliveryOutcome::Accepted{..})); h.join().unwrap(); assert!(matches!(a.deliver(r).unwrap(),WakeDeliveryOutcome::Duplicate{..})); drop(d); }
#[test] fn rejects_wrong_slot_and_typed_failure_without_consuming_retry() { let r=request(8); let (d,p,h)=server(Some(HarnessEvent::DeliveryCompleted(DeliveryCompleted{harness:r.harness.clone(),message_slot:MessageSlot::new(9)}))); let mut a=WakeDeliveryAdapter::new(p,Duration::from_millis(100)); assert_eq!(a.deliver(r.clone()),Err(WakeDeliveryFailure::WrongReply)); h.join().unwrap(); drop(d); let (d,p,h)=server(Some(HarnessEvent::DeliveryFailed(DeliveryFailed{harness:r.harness.clone(),message_slot:r.message_slot,reason:DeliveryFailureReason::TransportRejected}))); let mut a=WakeDeliveryAdapter::new(p,Duration::from_millis(100)); assert_eq!(a.deliver(r),Err(WakeDeliveryFailure::WrongReply)); h.join().unwrap(); drop(d); }
#[test] fn timeout_and_truncated_frame_fail_closed() { let r=request(10); let (d,p,h)=server(None); let mut a=WakeDeliveryAdapter::new(p,Duration::from_millis(20)); assert!(a.deliver(r.clone()).is_err()); h.join().unwrap(); drop(d); let dir=tempfile::tempdir().unwrap(); let p=dir.path().join("bad.sock"); let l=UnixListener::bind(&p).unwrap(); let h=thread::spawn(move||{let(mut s,_)=l.accept().unwrap();let mut n=[0;4];s.read_exact(&mut n).unwrap();let mut b=vec![0;u32::from_be_bytes(n)as usize];s.read_exact(&mut b).unwrap();s.write_all(&10u32.to_be_bytes()).unwrap();s.write_all(b"bad").unwrap();}); let mut a=WakeDeliveryAdapter::new(p,Duration::from_millis(100)); assert!(a.deliver(r).is_err()); h.join().unwrap(); }
#[test] fn wrong_harness_is_rejected() { let r=request(11); let (d,p,h)=server(Some(HarnessEvent::DeliveryCompleted(DeliveryCompleted{harness:HarnessName::new("other"),message_slot:r.message_slot}))); let mut a=WakeDeliveryAdapter::new(p,Duration::from_millis(100)); assert_eq!(a.deliver(r),Err(WakeDeliveryFailure::WrongReply)); h.join().unwrap(); drop(d); }
#[test] fn oversized_prefix_is_rejected_before_payload_read() { let r=request(12); let dir=tempfile::tempdir().unwrap(); let p=dir.path().join("large.sock"); let l=UnixListener::bind(&p).unwrap(); let h=thread::spawn(move||{let(mut s,_)=l.accept().unwrap();let mut n=[0;4];s.read_exact(&mut n).unwrap();let mut b=vec![0;u32::from_be_bytes(n)as usize];s.read_exact(&mut b).unwrap();s.write_all(&(1_048_577u32).to_be_bytes()).unwrap();}); let mut a=WakeDeliveryAdapter::new(p,Duration::from_millis(100)); assert_eq!(a.deliver(r),Err(WakeDeliveryFailure::Frame)); h.join().unwrap(); }
#[test] fn changed_body_for_accepted_slot_is_conflict() { let r=request(13); let (d,p,h)=server(Some(HarnessEvent::DeliveryCompleted(DeliveryCompleted{harness:r.harness.clone(),message_slot:r.message_slot}))); let mut a=WakeDeliveryAdapter::new(p,Duration::from_millis(100)); assert!(matches!(a.deliver(r.clone()),Ok(WakeDeliveryOutcome::Accepted{..}))); h.join().unwrap(); drop(d); let mut changed=r; changed.body="different".into(); changed.body_sha256="9d6f965ac832e40a5df6c06afe983e3b449c07b843ff51ce76204de05c690d11".into(); assert_eq!(a.deliver(changed),Err(WakeDeliveryFailure::Conflict)); }
